// RESTAURANTS
export const TOGGLE_RESTAURANT_MODAL = 'TOGGLE_RESTAURANT_MODAL';
export const SET_CURRENT_RESTAURANT = 'SET_CURRENT_RESTAURANT';
export const FETCH_RESTAURANTS_LIST = 'FETCH_RESTAURANTS_LIST';
export const FETCH_RESTAURANT_SUPPLIERS = 'FETCH_RESTAURANT_SUPPLIERS';
export const SET_CURRENT_RESTAURANT_SUPPLIER = 'SET_CURRENT_RESTAURANT_SUPPLIER';

// USER
export const GET_USERDATA = 'GET_USERDATA';
export const SET_USER_DATA = 'SET_USER_DATA';
export const SET_USER_TOKEN = 'SET_USER_TOKEN';

// PRODUCTS
export const SET_CURRENT_CATEGORY = 'SET_CURRENT_CATEGORY';
export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const FETCH_OFFERS = 'FETCH_OFFERS';
export const FETCH_TOP_OFFERS = 'FETCH_TOP_OFFERS';
export const SET_PRODUCT_FILTER = 'SET_PRODUCT_FILTER';
export const QUERY_SEARCH = 'QUERY_SEARCH';
export const WIPE_SEARCH = 'WIPE_SEARCH';

// SUPPLIERS
export const FETCH_SUPPLIERS = 'FETCH_SUPPLIERS';
export const FETCH_SUPPLIERS_ERROR = 'FETCH_SUPPLIERS_ERROR';
export const SET_ACTIVE_SUPPLIER = 'SET_ACTIVE_SUPPLIER';
export const SET_ACTIVE_SUPPLIER_ERROR = 'SET_ACTIVE_SUPPLIER_ERROR';

// CART
export const FETCH_CART = 'FETCH_CART';
export const UPDATE_CART = 'UPDATE_CART';
export const RESET_CART = 'RESET_CART';
export const REMOVE_PRODUCT = 'REMOVE_PRODUCT';

// MODELS
export const SET_CURRENT_MODEL = 'SET_CURRENT_MODEL';
export const FETCH_MODELS = 'FETCH_MODELS';
export const FETCH_MODELS_ERROR = 'FETCH_MODELS_ERROR';
export const FETCH_MODEL_CART = 'FETCH_MODEL_CART';
export const UPDATE_MODEL_CART = 'UPDATE_MODEL_CART';
export const RESET_MODEL_CART = 'RESET_MODEL_CART';
export const REMOVE_MODEL_ITEM = 'REMOVE_MODEL_ITEM';


// DELIVERIES
export const FETCH_DELIVERIES = 'FETCH_DELIVERIES';
